
CREATE INDEX index_GSTOCKITEMS_GTRANSTYPEID_STOCKID_GSTOCKITEMSL
  ON T_GSTOCKITEMS (GTRANSTYPEID,STOCKID,GSTOCKITEMSL);

  
  
  CREATE INDEX index_T_DSUBITEMS_DSUBITEMSID_DYELINEID_AUXTYPEID
  ON T_DSUBITEMS (DSUBITEMSID,DYELINEID,AUXTYPEID);

PROMPT create table T_KNITMACHINEINFOITEMS

CREATE INDEX index_T_KNITMACHINEINFOITEMS_PID_MACHINEID
  ON T_KNITMACHINEINFOITEMS (PID,MACHINEID);
  
  
  
PROMPT create table T_DINVOICEITEMS

CREATE INDEX index_T_DINVOICEITEMS_OrderNo
  ON T_DINVOICEITEMS (OrderNo);
  
  
 CREATE INDEX index_T_KNITSTOCKITEMS_OrderNo
  ON T_KNITSTOCKITEMS (OrderNo);
  
  
CREATE INDEX index_T_DINVOICEITEMS_SHADE
  ON T_DINVOICEITEMS (SHADE);
  
  
  CREATE INDEX index_T_ACCSTOCKITEMS_GORDERNO
  ON T_ACCSTOCKITEMS (GORDERNO);
  
  
    
  CREATE INDEX index_T_GAWORKORDER_GORDERNO
  ON T_GAWORKORDER (GORDERNO);
  
  
  CREATE INDEX index_T_WorkOrder_BUDGETID
  ON T_WorkOrder (BUDGETID);
  

  
  CREATE INDEX index_T_WorkOrder_GOrderRef
  ON T_WorkOrder (GarmentsOrderRef); 
  
  

CREATE INDEX index_T_KNITSTOCKITEMS_S_O_I
  ON T_KNITSTOCKITEMS (STOCKID,OrderNo,ORDERLINEITEM,FABRICTYPEID);
  
CREATE INDEX index_T_KNITSTOCK_S_K
  ON T_KNITSTOCK (STOCKID,KNTITRANSACTIONTYPEID);
  